name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile evilsanta2008v3.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: evilsanta2008v3-exe
          path: dist/*.exe
